In [229]:
import numpy as np
import pandas as pd
import matplotlib
from sklearn.model_selection import train_test_split
""" 
You are allowed to change the names of function "arguments" as per your convenience, 
but it should be meaningful.

E.g. y, y_train, y_test, output_var, target, output_label, ... are acceptable
but abc, a, b, etc. are not.
"""
def get_labeled_features(file_path):
    df = pd.read_csv('train.csv')
    df
    phi = df.drop('quality', axis = 1)
    phi = phi.drop('type', axis = 1)
    y = df['quality']
    var = pd.get_dummies(df['type'])
    phi = pd.concat([var,phi], axis='columns')
    phi_train, y_train, phi_dev, y_de = train_test_split(phi,y,test_size = 0.2)
    return phi_train, y_train, phi_dev, y_dev

In [230]:
def get_test_features(file_path):
    """Read test data, perform required preproccessing / augmentation
       and return final feature matrix.

    Args:
        file_path (str): path to test.csv

    Returns:
        phi_test: matrix of size (m,n) where m is number of test instances
                  and n is the dimension of the feature space.
    """
    df1 = pd.read_csv('train.csv')
    phi_test = df.drop('quality', axis = 1)
    return phi_test

In [231]:
def compute_RMSE(phi, w , y) :
    n = len(phi)
    for i in range(n):
        error = error + ((np.sum(w[i]*phi[i])-y)**2)
        
    return error

In [232]:
def generate_output(phi_test, w):
    y = np.sum(w*phi_test)
    dict = {'output':y}
    df = pd.DataFrame(dict)
    df.to_csv('output.csv')
    pass

In [290]:
import math
def gradient_descent(phi, y,phi2,y2) :
    w= np.zeros((13,))
    b=0
    k=0
    m=phi.shape[0]
    learning_rate=0.00005
    iterations=1000000000
    for i in range(iterations):
        y_pred=np.dot(phi,w)+b
        wd=-(learning_rate*np.mean(np.dot(phi.T,y-y_pred)))
        bd=-(learning_rate*(2/m)*np.sum((y-y_pred)))
        w=w-wd
        b=b-bd
        if math.isclose(cost, k, rel_tol=1e-15) :
            break
        k=cost
        print ("cost {}, iteration {}".format(cost, i))

    return w

def gradient_descent(phi, y, phi_dev, y_dev) :
    w0 = w1 = w2 = w3 = w4 = w5 = w6 = w7 =  w8= w9= w10= w11 = w12 = c =0
    rate = 0.1
    iteration = 1000
    n = len(phi)
    for i in range(iteration):
        y_pred = w0*phi[i][0] + w1*phi[i][1] + w2*phi[i][2] + w3*phi[i][3] + w4*phi[i][4] + w5*phi[i][5] + w6*phi[i][6] + w7*phi[i][7] + w8*phi[i][8] + w9*phi[i][9] + w10*phi[i][10] + w*phi[i][0]
        w = w - rate*(-2/n)*np.sum(phi*(y-y_pred))
        c = c - rate*(-2/n)*np.sum(y-y_pred)
    return w

In [291]:
#def closed_soln(phi, y):
    #"""Function returns the solution w for Xw = y."""
    #return np.linalg.pinv(phi).dot(y)
   


# def sgd(phi, y, phi_dev, y_dev) :
   # Implement stochastic gradient_descent using Mean Squared Error Loss
   # You may choose to use the dev set to determine point of convergence

    #return w


#def pnorm(phi, y, phi_dev, y_dev, p) :
   # Implement gradient_descent with p-norm regularization using Mean Squared Error Loss
   # You may choose to use the dev set to determine point of convergence

    #return w

In [292]:
def main():
    """ 
    The following steps will be run in sequence by the autograder.
    """
    ######## Task 2 #########
    phi, y, phi_dev, y_dev = get_labeled_features('train.csv')
   # w1 = closed_soln(phi, y)
    w2 = gradient_descent(phi, y, phi_dev, y_dev)
   # r1 = compute_RMSE(phi_dev, w1, y_dev)
    r2 = compute_RMSE(phi_dev, w2, y_dev)
   # print('1a: ')
    #print(abs(r1-r2))
   # w3 = sgd(phi, y, phi_dev, y_dev)
   # r3 = compute_RMSE(phi_dev, w3, y_dev)
   # print('1c: ')
    #print(abs(r2-r3))

    ######## Task 3 #########
  #  w_p2 = pnorm(phi, y, phi_dev, y_dev, 2)  
   # w_p4 = pnorm(phi, y, phi_dev, y_dev, 4)  
  #  r_p2 = compute_RMSE(phi_dev, w_p2, y_dev)
  #  r_p4 = compute_RMSE(phi_dev, w_p4, y_dev)
   # print('2: pnorm2')
   # print(r_p2)
   # print('2: pnorm4')
    # print(r_p4)
#
    ######## Task 6 #########
    
    # Add code to run your selected method here
    # print RMSE on dev set with this method

main()

ValueError: Unable to coerce to Series, length must be 13: given 3118

In [286]:
df = pd.read_csv('train.csv')
df
phi = df.drop('quality', axis = 1)
y = df['quality']
phi

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,white,6.8,0.46,0.26,6.3,0.147,49.0,159.0,0.99434,3.14,0.47,10.0
1,white,5.0,0.24,0.34,1.1,0.034,49.0,158.0,0.98774,3.32,0.32,13.1
2,white,7.9,0.19,0.45,1.5,0.045,17.0,96.0,0.99170,3.13,0.39,11.0
3,white,7.2,0.18,0.45,4.4,0.046,57.0,166.0,0.99430,3.13,0.62,11.2
4,white,7.9,0.42,0.49,8.2,0.056,32.0,164.0,0.99650,3.29,0.60,11.2
...,...,...,...,...,...,...,...,...,...,...,...,...
3893,white,7.5,0.42,0.45,9.1,0.029,20.0,125.0,0.99600,3.12,0.36,10.1
3894,white,6.8,0.37,0.51,11.8,0.044,62.0,163.0,0.99760,3.19,0.44,8.8
3895,white,6.7,0.25,0.33,2.9,0.057,52.0,173.0,0.99340,3.02,0.48,9.5
3896,white,6.5,0.21,0.51,17.6,0.045,34.0,125.0,0.99966,3.20,0.47,8.8
3897,white,7.9,0.35,0.24,15.6,0.072,44.0,229.0,0.99785,3.03,0.59,10.5

In [269]:
sz = phi.shape[1]
w = np.zeros(13) 
var = pd.get_dummies(df['type'])
var

      red  white
0       0      1
1       0      1
2       0      1
3       0      1
4       0      1
...   ...    ...
3893    0      1
3894    0      1
3895    0      1
3896    0      1
3897    0      1

[3898 rows x 2 columns]

In [270]:
phi = pd.concat([var,phi], axis='columns')

In [271]:
phi

,red,white,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0,1,white,6.8,0.46,0.26,6.3,0.147,49.0,159.0,0.99434,3.14,0.47,10.0
1,0,1,white,5.0,0.24,0.34,1.1,0.034,49.0,158.0,0.98774,3.32,0.32,13.1
2,0,1,white,7.9,0.19,0.45,1.5,0.045,17.0,96.0,0.99170,3.13,0.39,11.0
3,0,1,white,7.2,0.18,0.45,4.4,0.046,57.0,166.0,0.99430,3.13,0.62,11.2
4,0,1,white,7.9,0.42,0.49,8.2,0.056,32.0,164.0,0.99650,3.29,0.60,11.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3893,0,1,white,7.5,0.42,0.45,9.1,0.029,20.0,125.0,0.99600,3.12,0.36,10.1
3894,0,1,white,6.8,0.37,0.51,11.8,0.044,62.0,163.0,0.99760,3.19,0.44,8.8
3895,0,1,white,6.7,0.25,0.33,2.9,0.057,52.0,173.0,0.99340,3.02,0.48,9.5
3896,0,1,white,6.5,0.21,0.51,17.6,0.045,34.0,125.0,0.99966,3.20,0.47,8.8
3897,0,1,white,7.9,0.35,0.24,15.6,0.072,44.0,229.0,0.99785,3.03,0.59,10.5

In [272]:
phi = phi.drop('type', axis = 'columns')
phi

,red,white,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0,1,6.8,0.46,0.26,6.3,0.147,49.0,159.0,0.99434,3.14,0.47,10.0
1,0,1,5.0,0.24,0.34,1.1,0.034,49.0,158.0,0.98774,3.32,0.32,13.1
2,0,1,7.9,0.19,0.45,1.5,0.045,17.0,96.0,0.99170,3.13,0.39,11.0
3,0,1,7.2,0.18,0.45,4.4,0.046,57.0,166.0,0.99430,3.13,0.62,11.2
4,0,1,7.9,0.42,0.49,8.2,0.056,32.0,164.0,0.99650,3.29,0.60,11.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3893,0,1,7.5,0.42,0.45,9.1,0.029,20.0,125.0,0.99600,3.12,0.36,10.1
3894,0,1,6.8,0.37,0.51,11.8,0.044,62.0,163.0,0.99760,3.19,0.44,8.8
3895,0,1,6.7,0.25,0.33,2.9,0.057,52.0,173.0,0.99340,3.02,0.48,9.5
3896,0,1,6.5,0.21,0.51,17.6,0.045,34.0,125.0,0.99966,3.20,0.47,8.8
3897,0,1,7.9,0.35,0.24,15.6,0.072,44.0,229.0,0.99785,3.03,0.59,10.5

In [273]:
phi_train, y_train, phi_dev, y_de = train_test_split(phi,y,test_size = 0.2)

In [274]:
phi.shape

(3898, 13)

In [275]:
w.shape

(13,)

In [276]:
w= np.zeros((13,))
w.shape

(13,)

In [277]:
np.dot(phi, w)

array([0., 0., 0., ..., 0., 0., 0.])

In [278]:
df = pd.read_csv('train.csv')
df
phi = df.drop('quality', axis = 1)
phi = phi.drop('type', axis = 1)
y = df['quality']
var = pd.get_dummies(df['type'])
phi = pd.concat([var,phi], axis='columns')
phi_train, y_train, phi_dev, y_dev = train_test_split(phi,y,test_size = 0.2)
phi

,red,white,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0,1,6.8,0.46,0.26,6.3,0.147,49.0,159.0,0.99434,3.14,0.47,10.0
1,0,1,5.0,0.24,0.34,1.1,0.034,49.0,158.0,0.98774,3.32,0.32,13.1
2,0,1,7.9,0.19,0.45,1.5,0.045,17.0,96.0,0.99170,3.13,0.39,11.0
3,0,1,7.2,0.18,0.45,4.4,0.046,57.0,166.0,0.99430,3.13,0.62,11.2
4,0,1,7.9,0.42,0.49,8.2,0.056,32.0,164.0,0.99650,3.29,0.60,11.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3893,0,1,7.5,0.42,0.45,9.1,0.029,20.0,125.0,0.99600,3.12,0.36,10.1
3894,0,1,6.8,0.37,0.51,11.8,0.044,62.0,163.0,0.99760,3.19,0.44,8.8
3895,0,1,6.7,0.25,0.33,2.9,0.057,52.0,173.0,0.99340,3.02,0.48,9.5
3896,0,1,6.5,0.21,0.51,17.6,0.045,34.0,125.0,0.99966,3.20,0.47,8.8
3897,0,1,7.9,0.35,0.24,15.6,0.072,44.0,229.0,0.99785,3.03,0.59,10.5

In [279]:
y.shape
b = 1

In [281]:
y_pred = np.dot(phi,w) + b
y_pred.shape

(3898,)

In [282]:
y.shape

(3898,)

In [252]:
y-y_pred

0       4.0
1       6.0
2       5.0
3       5.0
4       6.0
       ...
3893    5.0
3894    4.0
3895    6.0
3896    5.0
3897    5.0
Name: quality, Length: 3898, dtype: float64

In [255]:
np.mean((y-y_pred))

4.819394561313494

In [257]:
np.dot(phi.T,y-y_pred)

array([4.49600000e+03, 1.42900000e+04, 1.35516550e+05, 6.26367000e+03,
       6.04998000e+03, 1.01003550e+05, 1.03340200e+03, 5.75815500e+05,
       2.15693550e+06, 1.86834339e+04, 6.04578700e+04, 9.97917000e+03,
       1.98718453e+05])